---
flavours:
  - architectures: [ 'amd64' ]
    platforms: [ metal ]
    extensions: [ [ ghost, server ] , [ chost, server ] , [ vhost, server ] ]
    modifiers: [ [ prod ] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    extensions: [ ['server'] ]
    modifiers: []
    platforms: [ base ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ base ]
    extensions: [ [_build, 'server'] ]
    modifiers: []
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ metal ]
    extensions: [ ['server'] ]
    modifiers: []
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ aws, azure, gcp, ali, openstack, vmware, kvm ]
    extensions: [ [ ghost, 'server' ] , [ chost, 'server' ] ]
    modifiers: [ [ prod ] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ aws, azure, gcp, ali, openstack, vmware, kvm ]
    extensions: [ ['server'] ]
    modifiers: []
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ gcp ]
    extensions: [ [ chost, 'server' ] ]
    modifiers: [ [ prod ] ]
    fails: [ unit ]
