apiVersion: 'tekton.dev/v1beta1'
kind: 'PipelineRun'
metadata:
  name: 'build-gardenlinux-snapshot-pipeline-run'
  namespace: 'gardenlinux-tkn'
spec:
  pipelineRef:
    name: 'build-gardenlinux-snapshot-pipeline'
